CREATE SEQUENCE ADVISOR_PK_ADVISOR_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE ADVISOR
(
  PK_ADVISOR BIGINT NOT NULL DEFAULT NEXTVAL('ADVISOR_PK_ADVISOR_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(100),
  TITLE CHARACTER VARYING(255),
  PROFILE_DESCRIPTION TEXT,
  BASIC_PICTURE_URL TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_ADVISOR PRIMARY KEY (PK_ADVISOR)
)
WITH (
  OIDS=FALSE
);