ALTER TABLE ADVISORY_POST ADD COLUMN HEAD_CONTENT TEXT;
ALTER TABLE ADVISORY_POST ADD COLUMN BACKGROUND1 TEXT;
ALTER TABLE ADVISORY_POST ADD COLUMN BACKGROUND2 TEXT;
ALTER TABLE ADVISORY_POST ADD COLUMN BOTTOM_CONTENT TEXT;
