CREATE SEQUENCE ADVISORY_PK_ADVISORY_POST_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE ADVISORY_POST
(
  PK_ADVISORY_POST BIGINT NOT NULL DEFAULT NEXTVAL('ADVISORY_PK_ADVISORY_POST_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(100),
  CONTENT TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  VALID INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_ADVISORY_POST PRIMARY KEY (PK_ADVISORY_POST)
)
WITH (
  OIDS=FALSE
);