ALTER TABLE ADVISORY ADD CONSTRAINT AD_FK_TUTOR_AU_PK_APP_USER FOREIGN KEY (FK_TUTOR) REFERENCES APP_USER (PK_APP_USER) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ADVISORY ADD COLUMN FK_CATEGORY BIGINT;
ALTER TABLE ADVISORY ADD COLUMN FK_ARTICLE BIGINT;

ALTER TABLE ADVISORY ADD CONSTRAINT AD_FK_CATEGORY_CAT_PK_CATEGORY FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORY (PK_CATEGORY) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ADVISORY ADD CONSTRAINT AD_FK_ARTICLE_AR_PK_ARTICLE FOREIGN KEY (FK_ARTICLE) REFERENCES ARTICLE (PK_ARTICLE) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;