ALTER TABLE ADVISORY_MENU ADD COLUMN MENU_TYPE INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ADVISORY_MENU ADD COLUMN ORDER_NO INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ADVISORY_MENU ADD COLUMN LINK TEXT;
ALTER TABLE ADVISORY_MENU ADD COLUMN FK_POST BIGINT REFERENCES ADVISORY_POST(PK_ADVISORY_POST);
