CREATE SEQUENCE ADVISORY_PK_ADVISORY_MENU_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE ADVISORY_MENU
(
  PK_ADVISORY_MENU BIGINT NOT NULL DEFAULT NEXTVAL('ADVISORY_PK_ADVISORY_MENU_SEQ'::REGCLASS),
  CODE CHARACTER VARYING(100) NOT NULL,
  NAME CHARACTER VARYING(100),
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  VALID INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_ADVISORY_MENU PRIMARY KEY (PK_ADVISORY_MENU)
)
WITH (
  OIDS=FALSE
);