ALTER TABLE APP_USER_ROLE DROP CONSTRAINT AUR_FK_APP_ROLE_AR_PK_APP_ROLE;
ALTER TABLE APP_USER_ROLE DROP CONSTRAINT AUR_FK_APP_USER_AU_PK_APP_USER;

ALTER TABLE APP_USER_ROLE ADD CONSTRAINT AUR_FK_APP_ROLE_AR_PK_APP_ROLE FOREIGN KEY (FK_APP_ROLE)
      REFERENCES APP_ROLE (PK_APP_ROLE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE APP_USER_ROLE ADD CONSTRAINT AUR_FK_APP_USER_AU_PK_APP_USER FOREIGN KEY (FK_APP_USER)
      REFERENCES APP_USER (PK_APP_USER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;