CREATE SEQUENCE ARTICLE_PK_ARTICLE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE ARTICLE
(
  PK_ARTICLE BIGINT NOT NULL DEFAULT NEXTVAL('ARTICLE_PK_ARTICLE_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(100),
  CONTENT TEXT,
  BASIC_PICTURE_URL TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_ARTICLE PRIMARY KEY (PK_ARTICLE)
)
WITH (
  OIDS=FALSE
);