CREATE SEQUENCE CATEGORY_PK_CATEGORY_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE CATEGORY
(
  PK_CATEGORY BIGINT NOT NULL DEFAULT NEXTVAL('CATEGORY_PK_CATEGORY_SEQ'::REGCLASS),
  CODE CHARACTER VARYING(100) NOT NULL,
  NAME CHARACTER VARYING(100),
  VALID INTEGER NOT NULL DEFAULT 1,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_CATEGORY PRIMARY KEY (PK_CATEGORY)
)
WITH (
  OIDS=FALSE
);