CREATE SEQUENCE SETTING_PK_CONTACT_SETTING_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE CONTACT_SETTING
(
  PK_CONTACT_SETTING BIGINT NOT NULL DEFAULT NEXTVAL('SETTING_PK_CONTACT_SETTING_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(100),
  ADDRESS TEXT,
  PHONE CHARACTER VARYING(100),
  FAX CHARACTER VARYING(100),
  WORKING_DAY1 CHARACTER VARYING(100),
  WORKING_DAY2 CHARACTER VARYING(100),
  WORKING_DAY3 CHARACTER VARYING(100),
  LONGITUDE CHARACTER VARYING(100),
  LATITUDE CHARACTER VARYING(100),
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_CONTACT_SETTING PRIMARY KEY (PK_CONTACT_SETTING)
)
WITH (
  OIDS=FALSE
);