CREATE SEQUENCE FAQ_PK_FAQ_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE FAQ
(
  PK_FAQ BIGINT NOT NULL DEFAULT NEXTVAL('FAQ_PK_FAQ_SEQ'::REGCLASS),
  FK_LOOKUP_FAQ_CATEGORY BIGINT REFERENCES LOOKUP(PK_LOOKUP),
  QUESTION TEXT,
  ANSWER TEXT,
  STATUS INTEGER NOT NULL DEFAULT 1,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_FAQ PRIMARY KEY (PK_FAQ)
)
WITH (
  OIDS=FALSE
);