CREATE SEQUENCE SETTING_PK_HOME_SETTING_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE HOME_SETTING
(
  PK_HOME_SETTING BIGINT NOT NULL DEFAULT NEXTVAL('SETTING_PK_HOME_SETTING_SEQ'::REGCLASS),
  CODE CHARACTER VARYING(100),
  BACKGROUND_IMAGE TEXT,
  TITLE_TEXT CHARACTER VARYING(100),
  SUB_TITLE_TEXT CHARACTER VARYING(100),
  LINK_URL TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_HOME_SETTING PRIMARY KEY (PK_HOME_SETTING)
)
WITH (
  OIDS=FALSE
);