CREATE SEQUENCE HOUSING_INDEX_PROVINCE_PK_HOUSING_INDEX_PROVINCE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE HOUSING_INDEX_PROVINCE
(
  PK_HOUSING_INDEX_PROVINCE BIGINT NOT NULL DEFAULT NEXTVAL('HOUSING_INDEX_PROVINCE_PK_HOUSING_INDEX_PROVINCE_SEQ'::REGCLASS),
  FK_HOUSING_INDEX BIGINT REFERENCES HOUSING_INDEX(PK_HOUSING_INDEX),
  FK_LOOKUP_PROVINCE BIGINT REFERENCES LOOKUP(PK_LOOKUP),
  CONSTRAINT PK_HOUSING_INDEX_PROVINCE PRIMARY KEY (PK_HOUSING_INDEX_PROVINCE)
)
WITH (
  OIDS=FALSE
);