ALTER TABLE RESEARCH_THEME DROP COLUMN description;
ALTER TABLE RESEARCH_THEME DROP COLUMN bg_image_url;
ALTER TABLE RESEARCH_THEME DROP COLUMN excerpt;
ALTER TABLE RESEARCH_THEME ADD pk_research_theme_parent bigint;