UPDATE APP_FUNCTION SET ACCESS_PAGE = '/do/researchDev/management/showList' WHERE PK_APP_FUNCTION = 830;
COMMIT;

DELETE FROM LOOKUP_GROUP WHERE LOOKUP_GROUP = 'ARTICLE_STATUS';
COMMIT;

INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('STATUS', 'Status', 'f', 'f');
COMMIT;

UPDATE LOOKUP SET LOOKUP_GROUP = 'STATUS' WHERE LOOKUP_GROUP = 'ARTICLE_STATUS';
COMMIT;

ALTER TABLE RESEARCH ADD COLUMN year integer;