DROP TABLE ADVISORY_MENU;
ALTER TABLE ADVISORY DROP COLUMN FK_ARTICLE;
DROP TABLE advisory_post;
DROP TABLE article_advisor;
DROP TABLE article;

DELETE FROM APP_ROLE_FUNCTION WHERE FK_APP_FUNCTION IN (730,740,940,950,960);
COMMIT;

DELETE FROM APP_FUNCTION WHERE PK_APP_FUNCTION IN (730,740,940,950,960);
COMMIT;

UPDATE APP_FUNCTION SET NAME = 'L. Category', DESCR = 'INT_LG_CATEGORY', ACCESS_PAGE = '/do/learning/category/showList' WHERE PK_APP_FUNCTION = 710;
UPDATE APP_FUNCTION SET NAME = 'L. Item', DESCR = 'INT_LG_ITEM', ACCESS_PAGE = '/do/learning/item/showList' WHERE PK_APP_FUNCTION = 720;
UPDATE APP_FUNCTION SET NAME = 'R&D. Category', DESCR = 'INT_RD_CATEGORY', ACCESS_PAGE = '/do/research/category/showList' WHERE PK_APP_FUNCTION = 810;
UPDATE APP_FUNCTION SET NAME = 'R&D. Item', DESCR = 'INT_RD_ITEM', ACCESS_PAGE = '/do/research/item/showList' WHERE PK_APP_FUNCTION = 820;
UPDATE APP_FUNCTION SET NAME = 'A. Category', DESCR = 'INT_ADV_CATEGORY', ACCESS_PAGE = '/do/advisory/category/showList' WHERE PK_APP_FUNCTION = 910;
UPDATE APP_FUNCTION SET NAME = 'A. Contact', DESCR = 'INT_ADV_CONTACT', ACCESS_PAGE = '/do/advisory/contact/showList' WHERE PK_APP_FUNCTION = 920;
UPDATE APP_FUNCTION SET NAME = 'A. Consulting', DESCR = 'INT_ADV_CONSULTING', ACCESS_PAGE = '/do/advisory/consulting/showList' WHERE PK_APP_FUNCTION = 930;
COMMIT;

ALTER TABLE ADVISORY RENAME TO ADVISORY_CONSULTING;

INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('LEARNING_METHOD', 'Learning Method', 't', 't');
INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('LEARNING_ORGANIZER', 'Learning Organizer', 't', 't');
INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('LEARNING_PAYMENT', 'Learning Payment', 't', 't');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_METHOD', 'KL', 'Klasik (Tatap Muka)', 'Klasik (Tatap Muka)', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_METHOD', 'EL', 'e-Learning', 'e-Learning', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_ORGANIZER', 'I', 'Internal', 'Internal', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_ORGANIZER', 'KPT', 'Kerjasama dengan Perguruan Tinggi', 'Kerjasama dengan Perguruan Tinggi', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_ORGANIZER', 'KP', 'Kerjasama dengan Partner', 'Kerjasama dengan Parter', 3, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_PAYMENT', 'G', 'Gratis', 'Gratis', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_PAYMENT', 'B', 'Berbayar', 'Berbayar', 2, 1, 'SYSTEM', 'SYSTEM');
COMMIT;

DELETE FROM LOOKUP_GROUP WHERE LOOKUP_GROUP = 'TAG_COURSE';
DELETE FROM LOOKUP WHERE LOOKUP_GROUP = 'TAG_COURSE';
COMMIT;

ALTER TABLE CATEGORY RENAME COLUMN CODE TO TYPE;
ALTER TABLE CATEGORY RENAME COLUMN VALID TO STATUS;
ALTER TABLE CATEGORY ADD COLUMN order_no integer;
ALTER TABLE CATEGORY ADD COLUMN permalink text;
ALTER TABLE CATEGORY RENAME COLUMN NAME TO TITLE;

UPDATE APP_FUNCTION SET ACCESS_PAGE = '/do/researchDev/category/showList' WHERE PK_APP_FUNCTION = 810;
UPDATE APP_FUNCTION SET ACCESS_PAGE = '/do/researchDev/item/showList' WHERE PK_APP_FUNCTION = 820;
UPDATE APP_FUNCTION SET ACCESS_PAGE = '/do/researchDev/researchManagement/showList' WHERE PK_APP_FUNCTION = 830;
COMMIT;