UPDATE APP_FUNCTION SET ACCESS_PAGE = '/do/researchDev/management/showList' WHERE PK_APP_FUNCTION = 830;
COMMIT;

DELETE FROM LOOKUP_GROUP WHERE LOOKUP_GROUP = 'ARTICLE_STATUS';
COMMIT;

INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('STATUS', 'Status', 'f', 'f');
COMMIT;

UPDATE LOOKUP SET LOOKUP_GROUP = 'STATUS' WHERE LOOKUP_GROUP = 'ARTICLE_STATUS';
COMMIT;

ALTER TABLE RESEARCH ADD COLUMN year integer;

INSERT INTO LINK_URL (TYPE, ORDER_NO, TITLE, URL, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('HI', '1', 'Link Housing Index', '#', 1, 'SYSTEM', 'SYSTEM');
COMMIT;

ALTER TABLE RESEARCH DROP CONSTRAINT research_fk_research_theme_fkey;
ALTER TABLE RESEARCH RENAME COLUMN fk_research_theme TO fk_category;
UPDATE RESEARCH SET fk_category = NULL;
COMMIT;
ALTER TABLE RESEARCH ADD CONSTRAINT research_fk_category_fkey FOREIGN KEY (fk_category) REFERENCES category (pk_category) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RESEARCH RENAME COLUMN year TO year_from;
ALTER TABLE RESEARCH ADD COLUMN year_to integer;
ALTER TABLE RESEARCH ADD COLUMN IS_ITEM BOOLEAN;
ALTER TABLE RESEARCH ALTER COLUMN IS_INTERNAL DROP NOT NULL;
ALTER TABLE RESEARCH ALTER COLUMN IS_INTERNAL DROP DEFAULT;

DROP VIEW VW_RESEARCH_DEVELOPMENT_REPORT;
CREATE OR REPLACE VIEW VW_RESEARCH_DEVELOPMENT_REPORT
AS
SELECT R.PK_RESEARCH, 
	R.IS_INTERNAL, 
	R.TITLE, 
	R.SUBTITLE, 
	R.IMAGE_URL, 
	R.DESCRIPTION,
	R.PRINCIPLE_PERMIT_FILE,
	R.PRINCIPLE_PERMIT_DESCRIPTION,
	R.PROCUREMENT_FILE,
	R.PROCUREMENT_DESCRIPTION,
	R.WORK_ORDER_FILE,
	R.WORK_ORDER_DESCRIPTION,
	R.VENDOR,
	R.PROJECT_VALUE,
	R.STATUS
FROM RESEARCH R;

ALTER TABLE RESEARCH DROP COLUMN fk_category;

CREATE TABLE research_category
(
  fk_research bigint NOT NULL,
  fk_category bigint NOT NULL,
  CONSTRAINT research_category_fk_research_fkey FOREIGN KEY (fk_research)
      REFERENCES research (pk_research) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT research_category_fk_category_fkey FOREIGN KEY (fk_category)
      REFERENCES category (pk_category) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

DROP TABLE research_keyword;
  
CREATE TABLE research_keyword
(
  pk_research_keyword bigint NOT NULL DEFAULT nextval('research_keyword_pk_research_keyword_seq'::regclass),
  fk_research bigint NOT NULL,
  keyword text,
  CONSTRAINT pk_research_keyword PRIMARY KEY (pk_research_keyword),
  CONSTRAINT research_keyword_fk_research_fkey FOREIGN KEY (fk_research)
      REFERENCES research (pk_research) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);