CREATE OR REPLACE VIEW vw_learning_item AS 
SELECT row_number() over() as PK, C.PK_CATEGORY,C.PERMALINK AS CATEGORY_PERMALINK,LI.PK_LEARNING_ITEM, LI.TITLE, LI.PERMALINK AS LEARNING_PERMALINK, LI.IMAGE_URL, LI.IMAGE_THUMB_URL, LI.DATE_FROM, LI.DATE_TO, 
LI.fk_lookup_method, LI.fk_lookup_organizer, LI.fk_lookup_payment,
CASE 
	WHEN (DATE_FROM < CURRENT_TIMESTAMP) THEN 'P' 
	WHEN (DATE_FROM >= CURRENT_TIMESTAMP) THEN 'F' 
END AS PERIOD,LI.STATUS
FROM LEARNING_ITEM LI 
INNER JOIN LEARNING_ITEM_CATEGORY LIC ON LIC.FK_LEARNING_ITEM = LI.PK_LEARNING_ITEM 
INNER JOIN CATEGORY C ON C.PK_CATEGORY = LIC.FK_CATEGORY;

INSERT INTO pages(title, status, permalink, order_no, type, created_by, creation_time, modified_by, modification_time)
    VALUES ('LEARNING',2,'learning',1,'PRL','SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP);
INSERT INTO pages(title, status, permalink, order_no, type, created_by, creation_time, modified_by, modification_time)
    VALUES ('ADVISORY',2,'advisory',2,'PRA','SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP);
INSERT INTO pages(title, status, permalink, order_no, type, created_by, creation_time, modified_by, modification_time)
    VALUES ('RESEARCH & DEVELOPMENT',2,'research-development',3,'PRR','SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP);
COMMIT;

ALTER TABLE PAGES ADD COLUMN IMAGE_THUMB_URL text;

ALTER TABLE LEARNING_ITEM ADD COLUMN CLOSING_DATE_REG timestamp with time zone;
ALTER TABLE LEARNING_ITEM ADD COLUMN LOCATION text;
ALTER TABLE LEARNING_ITEM ADD COLUMN ORGANIZER_DETAIL text;
ALTER TABLE LEARNING_ITEM ADD COLUMN PAYMENT_DESC text;
ALTER TABLE LEARNING_ITEM DROP COLUMN subtitle;
UPDATE LEARNING_ITEM SET PAYMENT_DESC = PAYMENT_DETAIL;
UPDATE LEARNING_ITEM SET PAYMENT_DETAIL = NULL;

CREATE SEQUENCE INTEGRATION_SCRIPT_PK_INTEGRATION_SCRIPT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE INTEGRATION_SCRIPT
(
  PK_INTEGRATION_SCRIPT BIGINT NOT NULL DEFAULT nextval('INTEGRATION_SCRIPT_PK_INTEGRATION_SCRIPT_SEQ'::regclass),
  TYPE INT NOT NULL,
  URL TEXT NOT NULL,
  POSITION INT NOT NULL,
  SCRIPT TEXT NOT NULL,
  STATUS INTEGER NOT NULL DEFAULT 1,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_INTEGRATION_SCRIPT PRIMARY KEY (PK_INTEGRATION_SCRIPT)
);

INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (450,400,'Integration Script','INT_FE_INTEGRATION_SCRIPT','/do/fed/integrationScript/showList','t',1,5);
COMMIT;

UPDATE LOOKUP_GROUP SET LOOKUP_GROUP = 'FAQ_TYPE', GROUP_DESCR = 'FAQ_TYPE' WHERE LOOKUP_GROUP = 'FAQ_CATEGORY';
UPDATE LOOKUP SET LOOKUP_GROUP = 'FAQ_TYPE' WHERE LOOKUP_GROUP = 'FAQ_CATEGORY';
COMMIT;

UPDATE APP_FUNCTION SET NAME = 'FAQ Category', DESCR = 'INT_MT_FAQ_CATEGORY', ACCESS_PAGE = '/do/master/faqCategory/showList' WHERE PK_APP_FUNCTION = 330; 
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES 
(340,300,'FAQ','INT_MT_FAQ','/do/master/faq/showList','t',1,4);
COMMIT;

UPDATE APP_FUNCTION SET NAME = 'FAQ Item', DESCR = 'INT_MT_FAQ_ITEM', ACCESS_PAGE = '/do/master/faqItem/showList' WHERE PK_APP_FUNCTION = 340;
COMMIT;

DROP TABLE faq;

CREATE TABLE faq
(
  pk_faq bigint NOT NULL DEFAULT nextval('faq_pk_faq_seq'::regclass),
  fk_category bigint,
  question text,
  answer text,
  status integer NOT NULL DEFAULT 1,
  created_by character varying(200) NOT NULL,
  creation_time timestamp with time zone NOT NULL DEFAULT now(),
  modified_by character varying(200) NOT NULL,
  modification_time timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_faq PRIMARY KEY (pk_faq),
  CONSTRAINT faq_fk_category_fkey FOREIGN KEY (fk_category)
      REFERENCES category (pk_category) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

DELETE FROM LOOKUP WHERE LOOKUP_GROUP = 'FAQ_TYPE';
COMMIT;