ALTER TABLE EVENT RENAME COLUMN EVENT_DATE TO EVENT_DATE_START;
ALTER TABLE EVENT ADD COLUMN EVENT_DATE_END timestamp with time zone NOT NULL DEFAULT now();
ALTER TABLE PROGRAM_ITEM ADD COLUMN IS_BACKGROUND_SLIDESHOW BOOLEAN;
ALTER TABLE PROGRAM_ITEM_IMAGE ADD COLUMN TYPE integer DEFAULT 0;
ALTER TABLE PROGRAM_ITEM_IMAGE ADD COLUMN ORDER_NO integer;
ALTER TABLE PROGRAM_ITEM_IMAGE ADD COLUMN status integer NOT NULL DEFAULT 1;

CREATE TABLE PROGRAM_ITEM_TESTIMONIAL
(
  fk_program_item bigint NOT NULL,
  fk_testimonial bigint NOT NULL,
  CONSTRAINT program_item_testimonial_fk_program_item_fkey FOREIGN KEY (fk_program_item)
      REFERENCES program_item (pk_program_item) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT program_item_testimonial_fk_testimonial_fkey FOREIGN KEY (fk_testimonial)
      REFERENCES testimonial (pk_testimonial) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

ALTER TABLE APP_PARAMETER ADD COLUMN ORDER_NO integer;
INSERT INTO APP_PARAMETER(NAME, VALUE, DESCR, IS_VIEWABLE, DATATYPE, CREATED_BY, MODIFIED_BY) 
VALUES ('SOCMED_URL_GOOGLE_PLUS', 'https://plus.google.com/', 'Link Akun Social Media Google Plus', 't', 3, 'SYSTEM', 'SYSTEM');
INSERT INTO APP_PARAMETER(NAME, VALUE, DESCR, IS_VIEWABLE, DATATYPE, CREATED_BY, MODIFIED_BY) 
VALUES ('SOCMED_URL_INSTAGRAM', 'https://www.instagram.com/', 'Link Akun Social Media Instagram', 't', 3, 'SYSTEM', 'SYSTEM');
ALTER TABLE APP_PARAMETER ADD COLUMN ATTRIBUTE text;
ALTER TABLE APP_PARAMETER ADD COLUMN IS_UPDATE_ORDER_NO boolean NOT NULL DEFAULT FALSE;

UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-facebook', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_FACEBOOK';
UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-twitter', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_TWITTER';
UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-youtube-play', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_YOUTUBE';
UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-linkedin ', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_LINKEDIN';
UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-google-plus', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_GOOGLE_PLUS';
UPDATE APP_PARAMETER SET ATTRIBUTE = 'fa-instagram', IS_UPDATE_ORDER_NO = 't' WHERE NAME = 'SOCMED_URL_INSTAGRAM';

CREATE OR REPLACE VIEW vw_search AS
SELECT row_number() OVER () AS PK, X.* FROM (
SELECT E.PERMALINK, '/page/engagement/'||E.PERMALINK AS LINK_DETAIL, E.TITLE, E.IMAGE_URL AS IMAGE_URL, 'Engagement' AS TYPE, 1 AS ORDER_NO FROM ENGAGEMENT E WHERE E.STATUS = 2
UNION
SELECT P.PERMALINK, '/page/program/'||P.PERMALINK AS LINK_DETAIL, P.TITLE, P.IMAGE_URL AS IMAGE_URL, 'Program HFC' AS TYPE, 2 AS ORDER_NO FROM PROGRAM_POST P WHERE P.STATUS = 2
UNION
SELECT D.PERMALINK, '/page/ebook/'||D.PERMALINK AS LINK_DETAIL, D.TITLE, D.COVER_IMAGE_URL AS IMAGE_URL, 'Digital Book' AS TYPE, 3 AS ORDER_NO FROM DIGITAL_BOOK D WHERE D.STATUS = 2
UNION
SELECT N.PERMALINK, '/page/news/'||N.PERMALINK AS LINK_DETAIL, N.TITLE, N.IMAGE_URL AS IMAGE_URL, 'News' AS TYPE, 4 AS ORDER_NO FROM NEWS N WHERE N.STATUS = 2
UNION
SELECT E.PERMALINK, '/page/event/'||E.PERMALINK AS LINK_DETAIL, E.TITLE, E.COVER_IMAGE_URL AS IMAGE_URL, 'Event' AS TYPE, 5 AS ORDER_NO FROM EVENT E WHERE E.STATUS = 2
UNION
SELECT C.PERMALINK,'/page/main-program/learning/'||C.PERMALINK AS LINK_DETAIL, INITCAP(LOWER(C.TITLE)), 
(CASE WHEN C.IMAGE_THUMB_URL IS NOT NULL THEN C.IMAGE_THUMB_URL
ELSE C.IMAGE_URL END) AS IMAGE_URL,
'Learning' AS TYPE, 6 AS ORDER_NO FROM CATEGORY C
WHERE C.STATUS = 2 AND C.TYPE = 'LG'
UNION
SELECT PI.PERMALINK,'/page/main-program/learning/'||C.PERMALINK||'/'||PI.PERMALINK AS LINK_DETAIL, PI.TITLE, 
(CASE WHEN PI.IMAGE_THUMB_URL IS NOT NULL THEN PI.IMAGE_THUMB_URL
ELSE PI.IMAGE_URL END) AS IMAGE_URL,
INITCAP(LOWER(c.title)) AS TYPE, 7 AS ORDER_NO FROM PROGRAM_ITEM PI 
INNER JOIN PROGRAM_ITEM_CATEGORY PIC ON PIC.FK_PROGRAM_ITEM = PI.PK_PROGRAM_ITEM
INNER JOIN CATEGORY C ON C.PK_CATEGORY = PIC.FK_CATEGORY
WHERE PI.STATUS = 2 AND PI.TYPE = 'LG'
UNION 
SELECT C.PERMALINK,'/page/main-program/learning/'||C.PERMALINK AS LINK_DETAIL, INITCAP(LOWER(C.TITLE)), 
(CASE WHEN C.IMAGE_THUMB_URL IS NOT NULL THEN C.IMAGE_THUMB_URL
ELSE C.IMAGE_URL END) AS IMAGE_URL,
'Advisory' AS TYPE, 8 AS ORDER_NO FROM CATEGORY C
WHERE C.STATUS = 2 AND C.TYPE = 'ADV'
UNION
SELECT PI.PERMALINK,'/page/main-program/advisory/'||C.PERMALINK||'/'||PI.PERMALINK AS LINK_DETAIL, PI.TITLE, 
(CASE WHEN PI.IMAGE_THUMB_URL IS NOT NULL THEN PI.IMAGE_THUMB_URL
ELSE PI.IMAGE_URL END) AS IMAGE_URL,
INITCAP(LOWER(c.title)) AS TYPE, 9 AS ORDER_NO FROM PROGRAM_ITEM PI 
INNER JOIN PROGRAM_ITEM_CATEGORY PIC ON PIC.FK_PROGRAM_ITEM = PI.PK_PROGRAM_ITEM
INNER JOIN CATEGORY C ON C.PK_CATEGORY = PIC.FK_CATEGORY
WHERE PI.STATUS = 2 AND PI.TYPE = 'ADV'
UNION 
SELECT C.PERMALINK,'/page/main-program/research-development/'||C.PERMALINK AS LINK_DETAIL, INITCAP(LOWER(C.TITLE)), 
(CASE WHEN C.IMAGE_THUMB_URL IS NOT NULL THEN C.IMAGE_THUMB_URL
ELSE C.IMAGE_URL END) AS IMAGE_URL,
'Research & Development' AS TYPE, 10 AS ORDER_NO FROM CATEGORY C
WHERE C.STATUS = 2 AND C.TYPE = 'RND'
UNION
SELECT R.PERMALINK,'/page/main-program/research-development/'||C.PERMALINK||'/'||R.PERMALINK AS LINK_DETAIL, R.TITLE, 
R.IMAGE_THUMB_URL AS IMAGE_URL, c.title AS TYPE, 11 AS ORDER_NO FROM RESEARCH R 
INNER JOIN RESEARCH_CATEGORY RC ON RC.FK_RESEARCH = R.PK_RESEARCH
INNER JOIN CATEGORY C ON C.PK_CATEGORY = RC.FK_CATEGORY
WHERE R.STATUS = 2
)X;

ALTER TABLE PROGRAM_ITEM RENAME COLUMN brochure_url TO brochure_url1;
ALTER TABLE PROGRAM_ITEM ADD COLUMN brochure_url2 text;
ALTER TABLE PROGRAM_ITEM_IMAGE DROP COLUMN image_thumb_url;
ALTER TABLE PROGRAM_ITEM_IMAGE DROP COLUMN status;