CREATE OR REPLACE VIEW vw_search AS 
SELECT row_number() OVER () AS PK, X.* FROM (
SELECT E.PERMALINK, '/page/engagement/'||E.PERMALINK AS LINK_DETAIL, E.TITLE, 'ENGAGEMENT' AS TYPE, 1 AS ORDER_NO FROM ENGAGEMENT E WHERE E.STATUS = 2
UNION
SELECT P.PERMALINK, '/page/program/'||P.PERMALINK AS LINK_DETAIL, P.TITLE, 'PROGRAM_POST' AS TYPE, 2 AS ORDER_NO FROM PROGRAM_POST P WHERE P.STATUS = 2
UNION
SELECT D.PERMALINK, '/page/ebook/'||D.PERMALINK AS LINK_DETAIL, D.TITLE, 'DIGITAL_BOOK' AS TYPE, 3 AS ORDER_NO FROM DIGITAL_BOOK D WHERE D.STATUS = 2
UNION
SELECT N.PERMALINK, '/page/news/'||N.PERMALINK AS LINK_DETAIL, N.TITLE, 'NEWS' AS TYPE, 4 AS ORDER_NO FROM NEWS N WHERE N.STATUS = 2
UNION
SELECT E.PERMALINK, '/page/event/'||E.PERMALINK AS LINK_DETAIL, E.TITLE, 'EVENT' AS TYPE, 5 AS ORDER_NO FROM EVENT E WHERE E.STATUS = 2
UNION
SELECT PI.PERMALINK,'/page/main-program/learning/'||C.PERMALINK||'/'||PI.PERMALINK AS LINK_DETAIL, PI.TITLE, 'LEARNING' AS TYPE, 6 AS ORDER_NO FROM PROGRAM_ITEM PI 
INNER JOIN PROGRAM_ITEM_CATEGORY PIC ON PIC.FK_PROGRAM_ITEM = PI.PK_PROGRAM_ITEM
INNER JOIN CATEGORY C ON C.PK_CATEGORY = PIC.FK_CATEGORY
WHERE PI.STATUS = 2 AND PI.TYPE = 'LG'
UNION
SELECT PI.PERMALINK,'/page/main-program/advisory/'||C.PERMALINK||'/'||PI.PERMALINK AS LINK_DETAIL, PI.TITLE, 'LEARNING' AS TYPE, 7 AS ORDER_NO FROM PROGRAM_ITEM PI 
INNER JOIN PROGRAM_ITEM_CATEGORY PIC ON PIC.FK_PROGRAM_ITEM = PI.PK_PROGRAM_ITEM
INNER JOIN CATEGORY C ON C.PK_CATEGORY = PIC.FK_CATEGORY
WHERE PI.STATUS = 2 AND PI.TYPE = 'ADV'
UNION
SELECT R.PERMALINK,'/page/main-program/research-development/'||C.PERMALINK||'/'||R.PERMALINK AS LINK_DETAIL, R.TITLE, 'RESEARCH' AS TYPE, 8 AS ORDER_NO FROM RESEARCH R 
INNER JOIN RESEARCH_CATEGORY RC ON RC.FK_RESEARCH = R.PK_RESEARCH
INNER JOIN CATEGORY C ON C.PK_CATEGORY = RC.FK_CATEGORY
WHERE R.STATUS = 2
)X;

INSERT INTO APP_PARAMETER(NAME, VALUE, DESCR, IS_VIEWABLE, DATATYPE, CREATED_BY, MODIFIED_BY) 
VALUES ('LEARNING_ADVISORY_USER_DATA_FROM', 'AD,TC', 'Used by Learning & Advisory to get data user for Teacher/Advisor', 't', 3, 'SYSTEM', 'SYSTEM');

ALTER TABLE LINK_URL ADD COLUMN FK_LINK_URL_PARENT BIGINT;
ALTER TABLE LINK_URL ADD CONSTRAINT lu_fk_link_url_parent FOREIGN KEY (FK_LINK_URL_PARENT)
      REFERENCES link_url (pk_link_url) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
      
INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('PROFESSION', 'Profession', 't', 't');
INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('INFORMATION_FROM', 'Information From', 't', 't');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'MM', 'Mahasiswa/Mahasiswi', 'Mahasiswa/Mahasiswi', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'KY', 'Karyawan', 'Karyawan', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'DV', 'Developer/Calon Developer/Pegawai Developer', 'Developer/Calon Developer/Pegawai Developer', 3, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'WU', 'Wirausaha', 'Wirausaha', 4, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'MU', 'Masyarakat Umum', 'Masyarakat Umum', 5, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('PROFESSION', 'LN', 'Lainnya', 'Lainnya', 6, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'WB', 'Website', 'Website', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'GG', 'Google', 'Google', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'EM', 'Email', 'Email', 3, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'SM', 'Social Media', 'Social Media', 4, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'MM', 'Media Massa', 'Media Massa', 5, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'TM', 'Teman', 'Teman', 6, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('INFORMATION_FROM', 'LN', 'Lainnya', 'Lainnya', 7, 1, 'SYSTEM', 'SYSTEM');

ALTER TABLE CONTACT ADD COLUMN INFORMATION_FROM text;

INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('CATEGORY_HELP', 'RD', 'Request-Download', 'Mengajukan Download File', 2, 1, 'SYSTEM', 'SYSTEM');
UPDATE LOOKUP SET ORDER_NO = 3 WHERE LOOKUP_GROUP = 'CATEGORY_HELP' AND CODE = 'MM';
UPDATE LOOKUP SET ORDER_NO = 4 WHERE LOOKUP_GROUP = 'CATEGORY_HELP' AND CODE = 'CC';

UPDATE LOOKUP SET USAGE = 'CONTACT' WHERE LOOKUP_GROUP = 'CATEGORY_HELP' AND CODE = 'RD';

