ALTER TABLE APP_FUNCTION ADD COLUMN IS_MENU boolean DEFAULT false;
UPDATE APP_FUNCTION SET IS_MENU = true;
UPDATE APP_FUNCTION SET IS_MENU = false WHERE FK_APP_FUNCTION_PARENT = 100;

ALTER TABLE app_user DROP CONSTRAINT app_user_unique_email;