CREATE SEQUENCE TESTIMONIAL_PK_TESTIMONIAL_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE TESTIMONIAL
(
  PK_TESTIMONIAL BIGINT NOT NULL DEFAULT NEXTVAL('TESTIMONIAL_PK_TESTIMONIAL_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(255) NOT NULL,
  TITLE TEXT,
  PHOTO_URL TEXT,
  DESCRIPTION TEXT NOT NULL,
  TESTIMONIAL_DATE TIMESTAMP WITH TIME ZONE NULL,
  STATUS INTEGER NOT NULL DEFAULT 1,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_TESTIMONIAL PRIMARY KEY (PK_TESTIMONIAL)
)
WITH (
  OIDS=FALSE
);