CREATE OR REPLACE VIEW VW_RESEARCH_DEVELOPMENT_REPORT
AS
SELECT R.PK_RESEARCH, 
	R.IS_INTERNAL, 
	R.TITLE, 
	R.SUBTITLE, 
	R.IMAGE_URL, 
	R.DESCRIPTION,
	R.PRINCIPLE_PERMIT_FILE,
	R.PRINCIPLE_PERMIT_DESCRIPTION,
	R.PROCUREMENT_FILE,
	R.PROCUREMENT_DESCRIPTION,
	R.WORK_ORDER_FILE,
	R.WORK_ORDER_DESCRIPTION,
	R.VENDOR,
	R.PROJECT_VALUE,
	R.STATUS
FROM RESEARCH R;