CREATE OR REPLACE VIEW VW_STUDENT_REPORT
AS
SELECT S.PK_STUDENT, 
	S.NAME,
	S.BIRTH_DATE, 
	S.BIRTH_PLACE, 
	LO.NAME as GENDER, 
	S.PHONE_NUMBER, 
	S.EMAIL,
	S.ADDRESS,
	S.STATUS
FROM STUDENT S
LEFT JOIN LOOKUP LO ON LO.PK_LOOKUP = S.FK_LOOKUP_GENDER;;
