ALTER TABLE COMPANY_MACHINERY ADD FK_COMPANY_PRODUCT_FROM bigint;
ALTER TABLE COMPANY_MACHINERY ADD CONSTRAINT CM_FK_COMPANY_PRODUCT_FROM FOREIGN KEY (FK_COMPANY_PRODUCT_FROM)
      REFERENCES COMPANY_PRODUCT (PK_COMPANY_PRODUCT) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
	  
ALTER TABLE COMPANY_MACHINERY ADD FK_COMPANY_PRODUCT_TO bigint;
ALTER TABLE COMPANY_MACHINERY ADD CONSTRAINT CM_FK_COMPANY_PRODUCT_TO FOREIGN KEY (FK_COMPANY_PRODUCT_TO)
      REFERENCES COMPANY_PRODUCT (PK_COMPANY_PRODUCT) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;