ALTER TABLE lookup_address ADD COLUMN order_no bigint;

ALTER TABLE LOOKUP_ADDRESS ADD STATUS INTEGER NOT NULL DEFAULT 1;
UPDATE LOOKUP_ADDRESS SET STATUS = 1 where IS_ACTIVE = true;
UPDATE LOOKUP_ADDRESS SET STATUS = 0 where IS_ACTIVE = false;
ALTER TABLE LOOKUP_ADDRESS DROP COLUMN IS_ACTIVE;

