INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1, null, 'Internal Function', 'INT_INTERNAL_FUNCTION', null, true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (100, 1, 'Dashboard', 'INT_DASHBOARD', '/do/dashboard', true, 1, 1);