TRUNCATE TABLE APP_ROLE_FUNCTION;

ALTER TABLE app_function DROP CONSTRAINT af_fk_app_function_parent_af_pk_app_function;
ALTER TABLE app_role_function DROP CONSTRAINT arf_fk_app_function_af_pk_app_function;
ALTER TABLE app_function DROP CONSTRAINT pk_app_function;
ALTER TABLE app_function ALTER COLUMN PK_APP_FUNCTION DROP DEFAULT; 
DROP SEQUENCE app_function_pk_app_function_seq;
ALTER TABLE app_function
  ADD CONSTRAINT pk_app_function_temp PRIMARY KEY(descr);

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1200, ORDER_NO = 12 WHERE DESCR = 'INT_CONTACT_US';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1210, FK_APP_FUNCTION_PARENT = 1200 WHERE DESCR = 'INT_CU_MAINTENANCE';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1220, FK_APP_FUNCTION_PARENT = 1200 WHERE DESCR = 'INT_CU_USER_CONTACT';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1100, ORDER_NO = 11 WHERE DESCR = 'INT_STUDENT_DATABASE';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1110, FK_APP_FUNCTION_PARENT = 1100 WHERE DESCR = 'INT_SD_MAINTENANCE';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1120, FK_APP_FUNCTION_PARENT = 1100 WHERE DESCR = 'INT_SD_UPDATE_LEARNING';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1000, ORDER_NO = 10 WHERE DESCR = 'INT_ADVISORY';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1010, FK_APP_FUNCTION_PARENT = 1000, ORDER_NO = 1 WHERE DESCR = 'INT_ADVISORY_SUB_MENU';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1020, FK_APP_FUNCTION_PARENT = 1000, ORDER_NO = 2 WHERE DESCR = 'INT_ADVISORY_COMMON_POST';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1030, FK_APP_FUNCTION_PARENT = 1000, ORDER_NO = 3 WHERE DESCR = 'INT_ADVISORY_CATEGORY';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1040, FK_APP_FUNCTION_PARENT = 1000, ORDER_NO = 4 WHERE DESCR = 'INT_ADVISORY_ISSUE_INSIGHT';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 1050, FK_APP_FUNCTION_PARENT = 1000, ORDER_NO = 5 WHERE DESCR = 'INT_ADVISORY_CONSULTING';
DELETE FROM APP_FUNCTION WHERE DESCR = 'INT_ADVISORY_ADVISOR';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 900, ORDER_NO = 9 WHERE DESCR = 'INT_RESEARCH';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 910, FK_APP_FUNCTION_PARENT = 900 WHERE DESCR = 'INT_RESEARCH_THEME';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 920, FK_APP_FUNCTION_PARENT = 900 WHERE DESCR = 'INT_RESEARCH_MAINTENANCE';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 930, FK_APP_FUNCTION_PARENT = 900 WHERE DESCR = 'INT_RESEARCH_MANAGEMENT';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 800, ORDER_NO = 8 WHERE DESCR = 'INT_LEARNING';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 810, FK_APP_FUNCTION_PARENT = 800 WHERE DESCR = 'INT_LEARNING_PROGRAM';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 820, FK_APP_FUNCTION_PARENT = 800 WHERE DESCR = 'INT_LEARNING_COURSE_TAG';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 830, FK_APP_FUNCTION_PARENT = 800 WHERE DESCR = 'INT_LEARNING_COURSE';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 700, ORDER_NO = 7 WHERE DESCR = 'INT_PUBLICATION';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 710, FK_APP_FUNCTION_PARENT = 700 WHERE DESCR = 'INT_PUB_EBOOK';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 720, FK_APP_FUNCTION_PARENT = 700, ACCESS_PAGE='/do/publication/news/showList' WHERE DESCR = 'INT_PUB_NEWS';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 730, FK_APP_FUNCTION_PARENT = 700, ACCESS_PAGE='/do/publication/event/showList' WHERE DESCR = 'INT_PUB_EVENT';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 600, ORDER_NO = 6 WHERE DESCR = 'INT_ACTIVITY';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 610, FK_APP_FUNCTION_PARENT = 600 WHERE DESCR = 'INT_ACT_ENGAGEMENT';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 620, FK_APP_FUNCTION_PARENT = 600 WHERE DESCR = 'INT_ACT_PROGRAM';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 500, ORDER_NO = 5 WHERE DESCR = 'INT_ABOUT_US';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 510, FK_APP_FUNCTION_PARENT = 500 WHERE DESCR = 'INT_AU_COMMON_POST';

UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 400, ORDER_NO = 4 WHERE DESCR = 'INT_FRONT_END_DISPLAY';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 410, FK_APP_FUNCTION_PARENT = 400 WHERE DESCR = 'INT_FED_MENU';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 420, FK_APP_FUNCTION_PARENT = 400 WHERE DESCR = 'INT_FED_SLIDESHOW';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 430, FK_APP_FUNCTION_PARENT = 400 WHERE DESCR = 'INT_FED_BACKGROUND_IMAGE';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 440, FK_APP_FUNCTION_PARENT = 400 WHERE DESCR = 'INT_FED_HOME_SETTING';

UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/administrator/appRole/showList' WHERE DESCR = 'INT_APP_ROLE';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/administrator/user/showList' WHERE DESCR = 'INT_APP_USER';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/administrator/businessSetting/showList' WHERE DESCR = 'INT_BUSINESS_SETTING';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/administrator/referenceGroup/showList' WHERE DESCR = 'INT_REFERENCE';

UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/fed/menu/showList' WHERE DESCR = 'INT_FED_MENU';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/fed/slideshow/showList' WHERE DESCR = 'INT_FED_SLIDESHOW';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/fed/backgroundImage/showList' WHERE DESCR = 'INT_FED_BACKGROUND_IMAGE';
UPDATE APP_FUNCTION SET ACCESS_PAGE='/do/fed/homeSetting/showList' WHERE DESCR = 'INT_FED_HOME_SETTING';

COMMIT;

ALTER TABLE app_function DROP CONSTRAINT pk_app_function_temp;

ALTER TABLE app_function
  ADD CONSTRAINT pk_app_function PRIMARY KEY(pk_app_function);
ALTER TABLE app_role_function
  ADD CONSTRAINT arf_fk_app_function_af_pk_app_function FOREIGN KEY (fk_app_function)
      REFERENCES app_function (pk_app_function) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE app_function
  ADD CONSTRAINT af_fk_app_function_parent_af_pk_app_function FOREIGN KEY (fk_app_function_parent)
      REFERENCES app_function (pk_app_function) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
  
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (300, 1, 'Master', 'INT_MASTER', '#', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (310, 300, 'Testimonial', 'INT_TESTIMONIAL', '/do/master/testimonial/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (320, 300, 'FAQ', 'INT_FAQ', '/do/master/faq/showList', true, 1, 2);

INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (740, 700, 'Housing Index', 'INT_PUB_HOUSING_INDEX', '/do/publication/housingIndex/showList', true, 1, 4);

INSERT INTO APP_ROLE_FUNCTION(FK_APP_ROLE, FK_APP_FUNCTION) (SELECT (SELECT PK_APP_ROLE FROM APP_ROLE WHERE CODE = 'SA'), PK_APP_FUNCTION FROM APP_FUNCTION);

INSERT INTO APP_ROLE_FUNCTION(FK_APP_ROLE, FK_APP_FUNCTION) (SELECT (SELECT PK_APP_ROLE FROM APP_ROLE WHERE CODE = 'AD'), PK_APP_FUNCTION FROM APP_FUNCTION WHERE DESCR IN ('INT_ADVISORY','INT_ADVISORY_ISSUE_INSIGHT','INT_ADVISORY_CONSULTING'));

COMMIT;
