DELETE FROM APP_ROLE_FUNCTION WHERE FK_APP_FUNCTION = 250;
DELETE FROM APP_FUNCTION WHERE PK_APP_FUNCTION = 250;

UPDATE APP_FUNCTION SET DESCR = 'INT_FRONT_END_DISPLAY' WHERE PK_APP_FUNCTION = 300;

UPDATE APP_FUNCTION SET DESCR = 'INT_FED_MENU' WHERE PK_APP_FUNCTION = 310;
UPDATE APP_FUNCTION SET DESCR = 'INT_FED_SLIDESHOW' WHERE PK_APP_FUNCTION = 320;
UPDATE APP_FUNCTION SET DESCR = 'INT_FED_BACKGROUND_IMAGE' WHERE PK_APP_FUNCTION = 330;
UPDATE APP_FUNCTION SET DESCR = 'INT_FED_HOME_SETTING' WHERE PK_APP_FUNCTION = 340;

UPDATE APP_FUNCTION SET NAME = 'Common Post' WHERE PK_APP_FUNCTION = 410;
UPDATE APP_FUNCTION SET NAME = 'Maintenance' WHERE PK_APP_FUNCTION = 1110;

TRUNCATE APP_ROLE_FUNCTION;

UPDATE APP_FUNCTION SET access_page = '/do/contactUs/userContact/showList' WHERE PK_APP_FUNCTION = 1120;
UPDATE APP_FUNCTION SET access_page = '/do/contactUs/maintenance/showDetail' WHERE PK_APP_FUNCTION = 1110;
UPDATE APP_FUNCTION SET access_page = '/do/research/researchManagement/showList' WHERE PK_APP_FUNCTION = 830;
UPDATE APP_FUNCTION SET access_page = '/do/student/database/showList' WHERE PK_APP_FUNCTION = 1010;
UPDATE APP_FUNCTION SET access_page = '/do/student/updateLearningStatus/showList' WHERE PK_APP_FUNCTION = 1020;

DELETE FROM APP_FUNCTION WHERE PK_APP_FUNCTION = 720;
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 720 WHERE descr = 'INT_LEARNING_COURSE_TAG';
UPDATE APP_FUNCTION SET PK_APP_FUNCTION = 730 WHERE descr = 'INT_LEARNING_COURSE';

INSERT INTO APP_ROLE_FUNCTION (FK_APP_ROLE, FK_APP_FUNCTION) SELECT '1', PK_APP_FUNCTION FROM APP_FUNCTION ORDER BY PK_APP_FUNCTION ASC;

UPDATE APP_FUNCTION SET NAME = 'Research & Dev.' WHERE PK_APP_FUNCTION = 800;
UPDATE APP_FUNCTION SET NAME = 'R&D Topic' WHERE PK_APP_FUNCTION = 810;
UPDATE APP_FUNCTION SET NAME = 'R&D Maintenance' WHERE PK_APP_FUNCTION = 820;
UPDATE APP_FUNCTION SET NAME = 'R&D Management' WHERE PK_APP_FUNCTION = 830;
UPDATE APP_FUNCTION SET NAME = 'S.D. Maintenance' WHERE PK_APP_FUNCTION = 1010;
UPDATE APP_FUNCTION SET NAME = 'C.U. Maintenance' WHERE PK_APP_FUNCTION = 1110;
UPDATE APP_FUNCTION SET NAME = 'Home Setting' WHERE PK_APP_FUNCTION = 340;