TRUNCATE app_role_function;
TRUNCATE app_function CASCADE;
ALTER SEQUENCE app_role_function_pk_app_role_function_seq RESTART WITH 1;

INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1,NULL,'Internal Function','INT_INTERNAL_FUNCTION','','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (100,1,'Dashboard','INT_DASHBOARD','/do/dashboard','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (110,100,'Statistik Contact Us','INT_DS_CONTACT_US','#','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (120,100,'Statistik Research & Development','INT_DS_RND','#','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (200,1,'Administrator','INT_ADMINISTRATOR','#','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (210,200,'App Role','INT_ADM_APP_ROLE','/do/administrator/appRole/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (220,200,'App User','INT_ADM_APP_USER','/do/administrator/user/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (230,200,'Business Setting','INT_ADM_BUS_SET','/do/administrator/businessSetting/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (240,200,'Reference','INT_ADM_REF','/do/administrator/referenceGroup/showList','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (300,1,'Master','INT_MASTER','#','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (310,300,'Program','INT_MT_PROGRAM','/do/master/program/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (320,300,'Testimonial','INT_MT_TESTIMONIAL','/do/master/testimonial/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (330,300,'FAQ','INT_MT_FAQ','/do/master/faq/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (400,1,'Front End Display','INT_FRONT_END_DISPLAY','#','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (410,400,'Menu Setting','INT_FE_MENU_SET','/do/fed/menuSetting/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (420,400,'Home Setting','INT_FE_HOME_SET','/do/fed/homeSetting/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (430,400,'Pages','INT_FE_PAGE','/do/fed/page/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (440,400,'Footer Link URL','INT_FE_FOOTER_LINK_URL','/do/fed/footerLinkUrl/showList','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (500,1,'About Us','INT_ABOUT_US','#','t',1,5);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (510,500,'Common Post','INT_AU_COMMON_POST','/do/aboutUs/commonPost/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (520,500,'Engagement','INT_AU_ENGAGEMENT','/do/aboutUs/engagement/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (530,500,'Program HFC','INT_AU_PROGRAM_HFC','/do/aboutUs/program/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (600,1,'Publication','INT_PUBLICATION','#','t',1,6);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (610,600,'eBook','INT_PB_EBOOK','/do/publication/digitalBook/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (620,600,'News','INT_PB_NEWS','/do/publication/news/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (630,600,'Event','INT_PB_EVENT','/do/publication/event/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (640,600,'Housing Index','INT_PB_HOUSING_IDX','/do/publication/housingIndex/showList','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (700,1,'Learning','INT_LEARNING','#','t',1,7);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (710,700,'Method','INT_LG_METHOD','/do/learning/method/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (720,700,'Organizer','INT_LG_ORGANIZER','/do/learning/organizer/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (730,700,'Category','INT_LG_CATEGORY','/do/learning/category/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (740,700,'Item','INT_LG_ITEM','/do/learning/item/showList','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (800,1,'Research & Dev.','INT_RESEARCH','#','t',1,8);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (810,800,'Theme','INT_RD_THEME','/do/research/researchTheme/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (820,800,'Maintenance','INT_RD_MAINTENANCE','/do/research/researchMaintenance/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (830,800,'Management','INT_RD_MANAGEMENT','/do/research/researchManagement/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (900,1,'Advisory','INT_ADVISORY','#','t',1,9);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (910,900,'Sub Menu','INT_ADV_SUB_MENU','/do/advisory/menu/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (920,900,'Advisory Pages','INT_ADV_PAGES','/do/advisory/post/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (930,900,'Article Category','INT_ADV_CATEGORY','/do/advisory/category/showList','t',1,3);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (940,900,'Issue and insights','INT_ADV_ISSUE_INSIGHT','/do/advisory/researchInsight/showList','t',1,4);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (950,900,'Contact','INT_ADV_CONTACT','/do/advisory/contact/showList','t',1,5);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (960,900,'Consulting','INT_ADV_CONSULTING','/do/advisory/consulting/showList','t',1,6);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1000,1,'Student Database','INT_STUDENT_DATABASE','#','t',1,10);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1010,1000,'Student Maintenance','INT_SD_MAINTENANCE','/do/student/database/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1020,1000,'Update Learning Status','INT_SD_UPDATE_LEARNING','/do/student/updateLearningStatus/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1100,1,'Contact Us','INT_CONTACT_US','#','t',1,11);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1110,1100,'Contact Screen','INT_CU_SCREEN','/do/contactUs/maintenance/showDetail','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1120,1100,'User Contact','INT_CU_USER_CONTACT','/do/contactUs/userContact/showList','t',1,2);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1200,1,'Report','INT_REPORT','#','t',1,12);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1210,1200,'Research & Dev','INT_RT_RND','/do/report/researchDevelopment/showList','t',1,1);
INSERT INTO app_function(pk_app_function,fk_app_function_parent, name, descr, access_page,is_active, user_type, order_no) VALUES (1220,1200,'Student','INT_RT_STUDENT','/do/report/student/showList','t',1,2);

COMMIT;

INSERT INTO APP_ROLE_FUNCTION(fk_app_role, fk_app_function)
SELECT (SELECT PK_APP_ROLE FROM APP_ROLE WHERE CODE = 'SA'), PK_APP_FUNCTION FROM APP_FUNCTION ORDER BY PK_APP_FUNCTION ASC;
COMMIT;
