INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1300, 1, 'Report', 'INT_REPORT', '#', true, 1, 13);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1310, 1300, 'Research & Dev', 'INT_REPORT_RND', '/do/report/researchDevelopment/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1320, 1300, 'Student', 'INT_REPORT_STUDENT', '/do/report/student/showList', true, 1, 2);

COMMIT;

INSERT INTO APP_ROLE_FUNCTION(FK_APP_ROLE, FK_APP_FUNCTION) (SELECT (SELECT PK_APP_ROLE FROM APP_ROLE WHERE CODE = 'SA'), PK_APP_FUNCTION FROM APP_FUNCTION WHERE
DESCR IN ('INT_REPORT','INT_REPORT_RND','INT_REPORT_STUDENT'));

COMMIT;