-- Advisor Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (950, 900, 'Advisor', 'INT_ADVISORY_ADVISOR', '/do/advisory/advisor/showList', true, 1, 5);



