INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('COURSE_BASIC_INFO_FIELD', 'D', 'Jumlah Tatap Muka', 'Jumlah Tatap Muka', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('COURSE_BASIC_INFO_FIELD', 'P', 'Lama Program', 'Lama Program', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('COURSE_BASIC_INFO_FIELD', 'DY', 'Hari Kegiatan', 'Hari Kegiatan', 3, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('COURSE_BASIC_INFO_FIELD', 'HA', 'Jam Kegiatan', 'Jam Kegiatan', 4, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('COURSE_BASIC_INFO_FIELD', 'SE', 'Sekretariat', 'Sekretariat', 5, 1, 'SYSTEM', 'SYSTEM');