INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('CATEGORY_HELP', 'MM', 'Input', 'Memberi Masukan', 5, 1, 'SYSTEM', 'SYSTEM');
COMMIT;

UPDATE LOOKUP SET USAGE = 'CONTACT' WHERE LOOKUP_GROUP = 'CATEGORY_HELP' AND CODE IN ('CC','PR','MM');

UPDATE LOOKUP SET NAME = 'Call-Center' WHERE LOOKUP_GROUP = 'CATEGORY_HELP' AND CODE = 'CC';