INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('NOTIFICATION_ACTION_TYPE', 'CO', 'Submit Contact Us Form', 'Submit Contact Us Form', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('NOTIFICATION_ACTION_TYPE', 'AD', 'Submit Advisory Form', 'Submit Advisory Form', 2, 1, 'SYSTEM', 'SYSTEM');
COMMIT;