DELETE FROM LOOKUP WHERE LOOKUP_GROUP = 'NEWS_STATUS';
DELETE FROM LOOKUP_GROUP WHERE LOOKUP_GROUP = 'NEWS_STATUS';
DELETE FROM LOOKUP WHERE LOOKUP_GROUP = 'EVENT_STATUS';
DELETE FROM LOOKUP_GROUP WHERE LOOKUP_GROUP = 'EVENT_STATUS';

INSERT INTO LOOKUP_GROUP (LOOKUP_GROUP, GROUP_DESCR, IS_UPDATEABLE, IS_VIEWABLE)
VALUES ('ARTICLE_STATUS', 'Article Status', 'f', 'f');

INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ARTICLE_STATUS', '0', 'Delete', 'Delete', 0, 0, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ARTICLE_STATUS', '1', 'Draft', 'Draft', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ARTICLE_STATUS', '2', 'Publish', 'Publish', 2, 1, 'SYSTEM', 'SYSTEM');

UPDATE ENGAGEMENT SET STATUS = 2;
UPDATE PROGRAM_POST SET STATUS = 2;
UPDATE DIGITAL_BOOK SET STATUS = 2;
UPDATE NEWS SET STATUS = 2;
UPDATE EVENT SET STATUS = 2;

COMMIT;