DROP TABLE GOODS_RECEIPT_NOTE;
DROP TABLE GOODS_RECEIPT_NOTE_ELEMENT;

CREATE TABLE GOODS_RECEIPT_NOTE 
   (	PK_GOODS_RECEIPT_NOTE bigint, 
	FK_COMPANY bigint,
	GRN_NUMBER character varying(5),
	FK_C_LOOKUP_GRN_FROM bigint,
	GRN_PLAN_NO character varying(6),  
	FK_PARTY_SUPPLIER bigint,
	FK_COMPANY_WAREHOUSE bigint,
	FK_C_LOOKUP_CURRENCY bigint,
	GRN_QTY numeric(24,4),
	GRN_SUBVALUE numeric(24,4),
	GRN_VAT numeric(24,4),
	GRN_VAT_VALUE numeric(24,4),
	GRN_TOTAL_VALUE numeric(24,4),
	GRN_DATE timestamp with time zone,
	FK_PURCHASE_ORDER bigint,
	FK_PARTY_REFERENCE bigint,
	GRN_IS_POSTED boolean,
	STATUS integer not null default 1,
	CREATED_BY character varying(255),
	MODIFIED_BY character varying(255),
	CREATION_TIME timestamp with time zone,
	MODIFICATION_TIME timestamp with time zone, 
	CONSTRAINT PK_GOODS_RECEIPT_NOTE PRIMARY KEY (PK_GOODS_RECEIPT_NOTE),
	CONSTRAINT grn_fk_company FOREIGN KEY (fk_company)
      REFERENCES company (pk_company) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_C_LOOKUP_GRN_FROM FOREIGN KEY (FK_C_LOOKUP_GRN_FROM)
      REFERENCES COMPANY_LOOKUP (PK_COMPANY_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_PARTY_SUPPLIER FOREIGN KEY (FK_PARTY_SUPPLIER)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_COMPANY_WAREHOUSE FOREIGN KEY (FK_COMPANY_WAREHOUSE)
      REFERENCES COMPANY_WAREHOUSE (PK_COMPANY_WAREHOUSE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	 CONSTRAINT GRN_FK_C_LOOKUP_CURRENCY FOREIGN KEY (FK_C_LOOKUP_CURRENCY)
      REFERENCES COMPANY_LOOKUP (PK_COMPANY_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_PURCHASE_ORDER FOREIGN KEY (FK_PURCHASE_ORDER)
      REFERENCES PURCHASE_ORDER (PK_PURCHASE_ORDER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_PARTY_REFERENCE FOREIGN KEY (FK_PARTY_REFERENCE)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
   ) ;
   
   CREATE TABLE GOODS_RECEIPT_NOTE_DETAIL(
	PK_GOODS_RECEIPT_NOTE_DETAIL bigint, 
	FK_GOODS_RECEIPT_NOTE bigint,
	SEQ_NO bigint,
	FK_COMPANY_PRODUCT bigint,
	FK_LOOKUP_UOM bigint,
	RECEIVED_QUANTITY numeric(24,4),
	RECEIVED_PRICE numeric(24,4),
	RECEIVED_VALUE numeric(24,4),
	CREATED_BY character varying(255),
	MODIFIED_BY character varying(255),
	CREATION_TIME timestamp with time zone,
	MODIFICATION_TIME timestamp with time zone,
	CONSTRAINT PK_GOODS_RECEIPT_NOTE_DETAIL PRIMARY KEY (PK_GOODS_RECEIPT_NOTE_DETAIL),
	CONSTRAINT GRND_FK_GOODS_RECEIPT_NOTE FOREIGN KEY (FK_GOODS_RECEIPT_NOTE)
      REFERENCES GOODS_RECEIPT_NOTE (PK_GOODS_RECEIPT_NOTE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_COMPANY_PRODUCT FOREIGN KEY (FK_COMPANY_PRODUCT)
      REFERENCES COMPANY_PRODUCT (PK_COMPANY_PRODUCT) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT GRN_FK_LOOKUP_UOM FOREIGN KEY (FK_LOOKUP_UOM)
      REFERENCES LOOKUP (PK_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
	);
	
drop sequence GOODS_RECEIPT_NOTE_ELEMENT_PK_GOODS_RECEIPT_NOTE_ELEMENT_SEQ;
create sequence goods_receipt_note_detail_pk_goods_receipt_note_detail_seq start 1;  
alter table GOODS_RECEIPT_NOTE_DETAIL alter column PK_GOODS_RECEIPT_NOTE_DETAIL set default nextval('goods_receipt_note_detail_pk_goods_receipt_note_detail_seq');
	
insert into lookup_group (lookup_group,group_descr, is_updateable, is_viewable)
values('GOODS_RECEIPT_FROM', 'Goods Receipt Source',false, true);

insert into lookup(lookup_group,code,name_id,descr,order_no,status,created_by,creation_time,modified_by,modification_time)
values('GOODS_RECEIPT_FROM','SU', 'Pemasok','Supplier',1,1,'SYSTEM',now(),'SYSTEM',now());
insert into lookup(lookup_group,code,name_id,descr,order_no,status,created_by,creation_time,modified_by,modification_time)
values('GOODS_RECEIPT_FROM','PR', 'Produksi', 'Production', 2,1,'SYSTEM',now(),'SYSTEM',now());

CREATE TABLE DISPATCH_ORDER_NOTE 
   (	PK_DISPATCH_ORDER_NOTE bigint, 
	FK_COMPANY bigint,
	DISPATCH_NUMBER character varying(5),
	FK_COMPANY_WAREHOUSE bigint,
	PICKING_NUMBER character varying(5),
	FK_PARTY_CUSTOMER bigint,
	FK_C_LOOKUP_CURRENCY bigint,
	PICKING_QTY numeric(24,4),
	PICKING_SUBVALUE numeric(24,4),
	PICKING_VAT numeric(24,4),
	PICKING_VAT_VALUE numeric(24,4),
	PICKING_TOTAL_VALUE numeric(24,4),
	PICKING_DATE timestamp with time zone,
	STATUS integer not null default 1,
	CREATED_BY character varying(255),
	MODIFIED_BY character varying(255),
	CREATION_TIME timestamp with time zone,
	MODIFICATION_TIME timestamp with time zone, 
	CONSTRAINT PK_DISPATCH_ORDER_NOTE PRIMARY KEY (PK_DISPATCH_ORDER_NOTE),
	CONSTRAINT don_fk_company FOREIGN KEY (fk_company)
      REFERENCES company (pk_company) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT DON_FK_PARTY_CUSTOMER FOREIGN KEY (FK_PARTY_CUSTOMER)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT DON_FK_COMPANY_WAREHOUSE FOREIGN KEY (FK_COMPANY_WAREHOUSE)
      REFERENCES COMPANY_WAREHOUSE (PK_COMPANY_WAREHOUSE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	 CONSTRAINT DON_FK_C_LOOKUP_CURRENCY FOREIGN KEY (FK_C_LOOKUP_CURRENCY)
      REFERENCES COMPANY_LOOKUP (PK_COMPANY_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
   ) ;
   
create sequence DISPATCH_ORDER_NOTE_PK_DISPATCH_ORDER_NOTE_SEQ start 1;  
alter table DISPATCH_ORDER_NOTE alter column PK_DISPATCH_ORDER_NOTE set default nextval('DISPATCH_ORDER_NOTE_PK_DISPATCH_ORDER_NOTE_SEQ');
   
   CREATE TABLE DISPATCH_ORDER_NOTE_DETAIL (
	PK_DISPATCH_ORDER_NOTE_DETAIL bigint, 
	FK_DISPATCH_ORDER_NOTE bigint,
	SEQ_NO bigint,
	FK_PARTY_SALES_ORDER bigint,
	FK_COMPANY_PRODUCT bigint,
	FK_LOOKUP_UOM bigint,
	DISPATCH_QUANTITY numeric(24,4),
	DISPATCH_PRICE numeric(24,4),
	DISPATCH_VALUE numeric(24,4),
	CREATED_BY character varying(255),
	MODIFIED_BY character varying(255),
	CREATION_TIME timestamp with time zone,
	MODIFICATION_TIME timestamp with time zone,
	CONSTRAINT PK_DISPATCH_ORDER_NOTE_DETAIL PRIMARY KEY (PK_DISPATCH_ORDER_NOTE_DETAIL),
	CONSTRAINT DOND_FK_DISPATCH_ORDER_NOTE FOREIGN KEY (FK_DISPATCH_ORDER_NOTE)
      REFERENCES DISPATCH_ORDER_NOTE (PK_DISPATCH_ORDER_NOTE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT DOND_FK_PARTY_SALES_ORDER FOREIGN KEY (FK_PARTY_SALES_ORDER)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT DOND_FK_COMPANY_PRODUCT FOREIGN KEY (FK_COMPANY_PRODUCT)
      REFERENCES COMPANY_PRODUCT (PK_COMPANY_PRODUCT) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT DOND_FK_LOOKUP_UOM FOREIGN KEY (FK_LOOKUP_UOM)
      REFERENCES LOOKUP (PK_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
	);
	
create sequence DISPATCH_ORDER_NOTE_DETAIL_PK_DISPATCH_ORDER_NOTE_DETAIL_SEQ start 1;  
alter table DISPATCH_ORDER_NOTE_DETAIL alter column PK_DISPATCH_ORDER_NOTE_DETAIL set default nextval('DISPATCH_ORDER_NOTE_DETAIL_PK_DISPATCH_ORDER_NOTE_DETAIL_SEQ');