INSERT INTO LOOKUP_GROUP VALUES ('TERM_OF_PAYMENT','TERM_OF_PAYMENT',TRUE,TRUE,TRUE);

UPDATE LOOKUP_GROUP SET LOOKUP_GROUP = 'ITEM_TYPE', GROUP_DESCR = 'ITEM_TYPE' WHERE LOOKUP_GROUP = 'PRODUCT_TYPE';
UPDATE LOOKUP SET LOOKUP_GROUP = 'ITEM_TYPE' WHERE LOOKUP_GROUP = 'PRODUCT_TYPE';
